export { Header } from "./header";
export type { HeaderProps } from "./header";
export { Main } from "./main";
export type { MainProps } from "./main";
export { NavGroup } from "./nav-group";
export type { NavGroupProps } from "./nav-group";
export { NavUser } from "./nav-user";
export type { NavUserProps } from "./nav-user";
export { ThemeSwitch } from "./theme-switch";
export type { NavItem, NavSubItem, NavGroup as NavGroupType } from "./types";
